### Obtener todos los películas
GET http://localhost:3000/movies

### Obtener todos los usuarios
GET http://localhost:3000/usuarios

// Búsquedas
### Categoría y título
GET http://localhost:3000/movies/search/

### Categoría
GET http://localhost:3000/movies/search/Terror

### Título
GET http://localhost:3000/movies/search/:

### Añadir películas al carrito mediante su ID (todo correcto)
POST http://localhost:3000/movies/cart
Content-Type: application/json

[
    "8841b088-a97d-4f14-8840-4b8f6bf0c607",
    "67154b1a-6c68-4496-b385-dafb44c7fe6a",
    "09011e15-c086-4ea7-9f69-f7a03bb22068"
]

### Añadir películas al carrito mediante su ID (Por lo menos un ID incorrecto)
POST http://localhost:3000/movies/cart
Content-Type: application/json

[
    "Id invalido",
    "67154b1a-6c68-4496-b385-dafb44c7fe6a"
]

### Añadir películas al carrito mediante su ID (todo incorrecto)
POST http://localhost:3000/movies/cart
Content-Type: application/json

### Obtener película mediante ID (correcto)
GET http://localhost:3000/movies/09011e15-c086-4ea7-9f69-f7a03bb22068

### Obtener película mediante ID (incorrecto)
GET http://localhost:3000/movies/7a519ffa-bee2-4bd7-af2d-6c6bfb81f45c

### Añadir un nuevo película (Admin y correcto)
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "Five Night's At Freddy's",
    "sinopsis": "El terrorífico fenómeno del videojuego de terror se transforma en un escalofriante espectáculo cinematográfico, Blumhouse (productora de M3GAN, El teléfono negro y El hombre invisible) lleva Five Nights at Freddy's a la gran pantalla. La película trata de un problemático guardia de seguridad que empieza a trabajar en Freddy Fazbear's Pizza. Mientras pasa su primera noche en el trabajo, se da cuenta de que el turno de noche en Freddy's no será tan fácil de superar.",
    "posterUrl": "https://m.media-amazon.com/images/M/MV5BYTI0ZmI4NDItZGFlZC00M2E4LWIyZWEtMTFhMjQwYmU4MGNlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    "genero": "Terror",
    "duration": 112,
    "reparto": "Josh Hutcherson, Elizabeth Lail, Piper Rubio, Mary Stuart Masterson, Matthew Lillard",
    "trailerIframe": "https://www.youtube.com/embed/FRffQncR1HQ?si=VuixvUC2TjQXEubM"
}

### Añadir una nueva función (Admin y correcto)
POST http://localhost:3001/admin/json
Content-Type: application/json
x-auth: admin

{
    "fechHora":"12",
    
}

### Añadir una nueva película (Sin admin)
POST http://localhost:3000/admin/movies

{
    "title": "película admin nuevo",
    "description": "película nuevo desde admin movies",
    "imageUrl": "EsteEsUnLinkGenerico.com",
    "unit": "unit",
    "stock": 69,
    "pricePerUnit": 24.7,
    "category": "Moded"
}

### Actualizar un película ya existente (Admin)
PUT http://localhost:3000/admin/movies/1a402515-bfae-478a-afd5-b01a8fd1b167
Content-Type: application/json
x-auth: admin

{
    "title": "película admin modificado",
    "description": "película modificado desde admin movies",
    "imageUrl": "EsteEsUnLinkGenericoYModificado.com",
    "category": "Moded"
}

### Actualizar un película ya existente (Sin admin)
PUT http://localhost:3000/admin/movies/1a402515-bfae-478a-afd5-b01a8fd1b167
Content-Type: application/json

{
    "title": "película admin modificado",
    "description": "película modificado desde admin movies",
    "imageUrl": "EsteEsUnLinkGenericoYModificado.com",
    "category": "Moded"
}

### Borrar un película (Con admin)
DELETE http://localhost:3000/admin/movies/1a402515-bfae-478a-afd5-b01a8fd1b167
x-auth: admin

### Borrar un película (Sin admin)
DELETE http://localhost:3000/admin/movies/1a402515-bfae-478a-afd5-b01a8fd1b167

### Ingresar a /
GET http://localhost:3000/ 

### Ingresar a /home
GET http://localhost:3000/home

### Ingresar a /shopping_cart
GET http://localhost:3000/shopping_cart

//Ignorar, población de mi archivo JSON con mis películas
### Añadir un nuevo película
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "Five Night's At Freddy's",
    "sinopsis": "El terrorífico fenómeno del videojuego de terror se transforma en un escalofriante espectáculo cinematográfico, Blumhouse (productora de M3GAN, El teléfono negro y El hombre invisible) lleva Five Nights at Freddy's a la gran pantalla. La película trata de un problemático guardia de seguridad que empieza a trabajar en Freddy Fazbear's Pizza. Mientras pasa su primera noche en el trabajo, se da cuenta de que el turno de noche en Freddy's no será tan fácil de superar.",
    "posterUrl": "https://m.media-amazon.com/images/M/MV5BYTI0ZmI4NDItZGFlZC00M2E4LWIyZWEtMTFhMjQwYmU4MGNlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    "genero": "Terror",
    "duration": 112,
    "reparto": "Josh Hutcherson, Elizabeth Lail, Piper Rubio, Mary Stuart Masterson, Matthew Lillard",
    "trailerIframe": "https://www.youtube.com/embed/FRffQncR1HQ?si=VuixvUC2TjQXEubM"
}

### Añadir un nuevo película
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "The Jester",
    "sinopsis": "Después de la reciente muerte de su padre, dos hermanas separadas se encuentran siendo acechadas por un ser malévolo conocido como El Bufón. Revelándose como algo más que un simple hombre enmascarado, la entidad maligna comienza a atormentar aún más a los habitantes de este pequeño pueblo en la noche de Halloween.",
    "posterUrl": "https://m.media-amazon.com/images/M/MV5BZDcyYzRiZmItMTliMS00M2JkLWE0MGMtOWFkMDJmOTAzY2IzXkEyXkFqcGdeQXVyOTMzOTMzMTg@._V1_FMjpg_UX1000_.jpg",
    "genero": "Terror",
    "duration": 90,
    "reparto": "Lelia Symington, Sam Lukowski, Michael Sheffield, Matt Servitto",
    "trailerIframe": "https://www.youtube.com/embed/FgLPG38ZX7E?si=BabLKSnH5Ux7vX88"
}

### Añadir un nuevo película
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "Los Asesinos de la Luna",
    "sinopsis": "En la década de 1920, los miembros de la tribu de nativos americanos del condado de Osage, en Oklahoma, son asesinados cuando se encuentra petróleo en sus tierras. El FBI establece una investigación para encontrar a los culpables.",
    "posterUrl": "https://dx35vtwkllhj9.cloudfront.net/paramountpictures/killers-of-the-flower-moon/images/regions/mx/onesheet.jpg",
    "genero": "Suspenso",
    "duration": 206,
    "reparto": "Leonardo DiCaprio, Lily Gladstone, Robert De Niro, Jesse Plemons, Brendan Fraser",
    "trailerIframe": "https://www.youtube.com/embed/57yrWZt5z2g?si=8GuKw4h2B8ybGJQN"
}

### Añadir un nuevo película
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "La Patrulla Canina: La superpelícula",
    "sinopsis": "Los cachorros obtienen superpoderes tras la caída de un meteorito en la ciudad, pero las cosas se complican cuando los villanos les roban sus superpoderes.",
    "posterUrl": "https://static.wikia.nocookie.net/doblaje/images/4/4e/F2XieuEXYAASUKW.jpeg/revision/latest?cb=20230731140231&path-prefix=es",
    "genero": "Aventura Infantil",
    "duration": 93,
    "reparto": "Taraji P. Henson, Kim Kardashian, Finn Lee-Epp, Ron Pardo",
    "trailerIframe": "https://www.youtube.com/embed/UDgjJ9XzgHk?si=-04mQODOX0Z5RAEI"
}

### Añadir un nuevo película
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "Los Juegos del Hambre Balada de Pájaros Cantores y Serpientes",
    "sinopsis": "En este regreso de los Juegos del Hambre, años antes de que se convirtiera en el presidente tirano de Panem, un joven Coriolanus Snow ver la oportunidad de un cambio de fortunas cuando es elegido para ser mentor de Lucy Gray Baird, la chica tributo del empobrecido Distrito 12.",
    "posterUrl": "https://static.wikia.nocookie.net/doblaje/images/4/48/LJDH-BPCS.jpg/revision/latest?cb=20230920170940&path-prefix=es",
    "genero": "Acción, Aventura",
    "duration": 159,
    "reparto": "Viola Davis, Peter Dinklage, Rachel Zegler, Tom Blyth",
    "trailerIframe": "https://www.youtube.com/embed/IWjAy4lIyoY?si=F1QX2fH9hVpGI8zc"
}

### Añadir un nuevo película
POST http://localhost:3000/admin/movies
Content-Type: application/json
x-auth: admin

{
    "titulo": "Napoleón",
    "sinopsis": "Napoleón es una epopeya de acción llena de espectáculo que detalla el accidentado ascenso y caída del emblemático emperador francés Napoleón Bonaparte. Con un impresionante escenario cinematográfico a gran escala orquestado por el legendario director Ridley Scott, la película capta la implacable travesía de Bonaparte hacia el poder a través del prisma de su adictiva y volátil relación con su único y verdadero amor, Josefina, mostrando sus visionarias tácticas militares y políticas plasmadas en algunas de las secuencias de batalla más dinámicas y realistas jamás filmadas.",
    "posterUrl": "https://palomaynacho-1f321.kxcdn.com/wp-content/uploads/2023/10/NUEVO-NPLN_Cannons_1080X1350-jpg.webp",
    "genero": "Acción, Drama",
    "duration": 158,
    "reparto": "Tahar Rahim, Ludivine Sagnier, Vanessa Kirby, Catherine Walker, Joaquin Phoenix",
    "trailerIframe": "https://www.youtube.com/embed/1DJYiG6wh0w?si=3Su2Xxlx1qigPMsY"
}

//Rutas de MongoDB
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "nombre": "Andrea",
    "email": "andrea@email.com",
    "password": "contraseña3"
}

###
GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users?email=andrea@email.com

###
GET http://localhost:3001/api/users/655e86f32343f2e9b2e55565

###
GET http://localhost:3001/api/movies

###
GET http://127.0.0.1:3001/api/salas

###
POST http://localhost:3001/api/pedidos/
Content-Type: application/json

{
    "tituloPelicula": "The Jester",
    "posterUrl": "https://m.media-amazon.com/images/M/MV5BZDcyYzRiZmItMTliMS00M2JkLWE0MGMtOWFkMDJmOTAzY2IzXkEyXkFqcGdeQXVyOTMzOTMzMTg@._V1_FMjpg_UX1000_.jpg",
    "nombreSucursal": "La Gran Plaza",
    "funcion": "20:15",
    "cantidadBoletos": "4",
    "asientosSeleccionados": "F2, F3, F4",
    "emailUsuario": "dluna2010@live.com"
}